/***************************************************************************************
    CLIENT
        Client Name
            
    PURPOSE
        {{ api_name }}            
    
    CHANGE LOG
        [[Version; Date; Author; Description]]
        v0.1; 2014/06/02; Carl Weiss/Forefront; Initial Build
***************************************************************************************/
@isTest
private class {{ api_name }} {
	
	@isTest static void test_method_one() {
		// Implement test code
	}
	
	@isTest static void test_method_two() {
		// Implement test code
	}
	
}