/**
  * @author User / Forefront
  * @version 1.0
  * 
  * <b> PURPOSE </b>
  * <p>
  *        Some Detailed Purpose of the Class, what it does and why. <p>
  *        Helpful hints for the next developer.<p>
  *        Business logic or use cases can be used.<p>
  * <p>
  * <b> TEST CLASS </b>
  * <p>
  *     Name of the test class<p>
  *     For Naming use the class MyApexClass_TEST<p>
  *  <p>
  *  <b> ENTRY POINTS </b>
  *  <p>
  *     How is this code called, if a VF controller which page calls it.  <p>
  * <p>
  * <b> CHANGE LOG </b>
  * <p>
  *    [[Version; Date; Author; Description]]<p>
  *     v1.0; Date;  User / Forefront; Initial Build<p>
  * <p>
  **/
public with sharing class {{ api_name }} {
	public {{ api_name }}() {
		
	}
}
