/**
  * Copyright (c) 2016 ForeFront, Inc. All Rights Reserved.
  * Subject to ForeFront, Inc. licensing.
  *
  * @author UserName/Forefront
  * @version 1.0
  * @description
  *
  * PURPOSE
  * 
  *    Provide test coverate for {{api_name}}
  *  
  * ENTRY POINTS 
  *  
  *    How is this code called, if a VF controller which page calls it.  
  * 
  * CHANGE LOG 
  * 
  *    [Version; Date; Author; Description]
  *    v1.0; Date;  UserName/Forefront; Initial Build
  * 
  **/
  
@isTest
private class {{ api_name }} {
	
	@isTest static void test_method_one() {
		// Implement test code
	}
	
	@isTest static void test_method_two() {
		// Implement test code
	}
	
}
