/**
  * @author UserName/Forefront
  * @version 1.0
  * @description
  *
  * PURPOSE
  * 
  *    Some Detailed Purpose of the Class, what it does and why. 
  *    Helpful hints for the next developer.
  *    Business logic or use cases can be used.
  * 
  * TEST CLASS 
  * 
  *    Name of the test class
  *    For Naming use the class {{ api_name }}_TEST
  *  
  * ENTRY POINTS 
  *  
  *    How is this code called, if a VF controller which page calls it.  
  * 
  * CHANGE LOG 
  * 
  *    [Version; Date; Author; Description]
  *    v1.0; Date;  UserName/Forefront; Initial Build
  * 
  **/
  
@isTest
private class {{ api_name }} {
	
	@isTest static void test_method_one() {
		// Implement test code
	}
	
	@isTest static void test_method_two() {
		// Implement test code
	}
	
}
